apiVersion: v1
kind: Secret
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5jbi1zaGFuZ2hhaS5hbGl5dW5jcy5jb20iOnsidXNlcm5hbWUiOiLprZTlipvosLfnp5HmioAiLCJwYXNzd29yZCI6IiNCdWdzZm9yJCIsImVtYWlsIjoieG1jaGVuQHlhaGFoYS5jb20iLCJhdXRoIjoiNmEyVTVZcWI2TEMzNTZlUjVvcUFPaU5DZFdkelptOXlKQT09In19fQ==
kind: Secret
metadata:
  name: regcred
  namespace: {{ .Values.namespace }}
type: kubernetes.io/dockerconfigjson