apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.serviceName }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: streaming-app
  type: ClusterIP
  ports:
    - port: 30332
      targetPort: 30332